# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(default='未设置', max_length=11, verbose_name='电话')),
                ('age', models.IntegerField(default=1, verbose_name='用户年龄')),
                ('gender', models.CharField(default=0, max_length=10, verbose_name='性别')),
                ('header', models.ImageField(default='static/images/default.jpg', upload_to='static/images/headers', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
