# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofus_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_verify',
            field=models.CharField(default=0, max_length=1, verbose_name='邮箱验证'),
        ),
    ]
