# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofus_blog', '0004_auto_20181128_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField()),
                ('publishTime', models.DateTimeField(auto_now_add=True, verbose_name='创建文章的时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='每次修改文章的时间')),
                ('Introduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章简介')),
            ],
        ),
        migrations.CreateModel(
            name='article_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofus_blog.Users', verbose_name='文章所属用户')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.article_type', verbose_name='分类'),
        ),
    ]
