# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_type',
            name='type_title',
            field=models.CharField(default='默认文集', max_length=20, verbose_name='分类名称'),
        ),
    ]
