# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20181130_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_type',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
